
package com.company;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateService", targetNamespace = "http://company.com/", wsdlLocation = "http://localhost:8081/ws/calc?wsdl")
public class CalculateService
    extends Service
{

    private final static URL CALCULATESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATESERVICE_EXCEPTION;
    private final static QName CALCULATESERVICE_QNAME = new QName("http://company.com/", "CalculateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/ws/calc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATESERVICE_WSDL_LOCATION = url;
        CALCULATESERVICE_EXCEPTION = e;
    }

    public CalculateService() {
        super(__getWsdlLocation(), CALCULATESERVICE_QNAME);
    }

    public CalculateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATESERVICE_QNAME, features);
    }

    public CalculateService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATESERVICE_QNAME);
    }

    public CalculateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATESERVICE_QNAME, features);
    }

    public CalculateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ICalculate
     */
    @WebEndpoint(name = "CalculatePort")
    public ICalculate getCalculatePort() {
        return super.getPort(new QName("http://company.com/", "CalculatePort"), ICalculate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalculate
     */
    @WebEndpoint(name = "CalculatePort")
    public ICalculate getCalculatePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://company.com/", "CalculatePort"), ICalculate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATESERVICE_EXCEPTION!= null) {
            throw CALCULATESERVICE_EXCEPTION;
        }
        return CALCULATESERVICE_WSDL_LOCATION;
    }

}
